#dingeling comment motherfucker.
---
- hosts: localhost
  
  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: include variables (free-form)
    include_vars: vars.yml
    no_log: "no"
    
  - name: permit ssh to bla
    panos_security_rule:
      operation: "add"
      ip_address: "{{ mgmt_ip }}"
      password: "{{ admin_password }}"
      rule_name: 'SSH permit'
      description: 'SSH rule test'
      source_zone: ['untrust']
      destination_zone: ['trust']
      source_ip: ['any']
      source_user: ['any']
      destination_ip: ['1.1.1.1']
      category: ['any']
      application: ['ssh']
      service: ['application-default']
      hip_profiles: ['any']
      action: 'allow'