# All Ansible playbooks start with: ---
---
# This defines which machines the playbook will run on
- hosts: localhost
  
  # This defines which libraries are used for the playbook
  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  # This defines the different actions of the playbook
  tasks:
  - name: include variables (free-form)
    include_vars: vars.yml
    no_log: "no"
    
  # This is the rule we will add to our palo alto
  - name: permit ssh to 1.1.1.1
    panos_security_rule:
      operation: "add"
      ip_address: "{{ mgmt_ip }}"
      password: "{{ admin_password }}"
      rule_name: 'SSH permit'
      description: 'SSH rule test'
      source_zone: ['untrust']
      destination_zone: ['trust']
      source_ip: ['any']
      source_user: ['any']
      destination_ip: ['1.1.1.1']
      category: ['any']
      application: ['ssh']
      service: ['application-default']
      hip_profiles: ['any']
      action: 'allow'